### ISSUE TITLE
页面显示的帖子最后编辑时间与实际时间不符

### ISSUE THREAD

**Issue by fkd151136** [Slontia/iCourse#80]
bug详情：2017.12.05 20时左右在“中国当代文明史”课程论坛上发了一个测试帖子，论坛主页面显示的编辑时间为2017.12.05 11:56:10 
版本号：eb73c0d
分析：可能是服务器的系统时间与北京时间不一致导致（目测是格林尼治时间），考虑到主要用户为北航学生，建议将服务器时间设置与北京时间同步~

**Comment by Slontia** [comment]
修改settings.py:
`TIME_ZONE = 'Asia/Shanghai'`
`USE_TZ = False`
