### ISSUE TITLE
跟帖正文框输入空格，会显示输入超出规定长度

### ISSUE THREAD

**Issue by fkd151136** [Slontia/iCourse#87]
- bug详情：进入软件工程基础（6系）的论坛，点击进入“为什么选择计算机”一贴，显示“已输入0个字符，还可以输入10000个字符”，在跟帖的正文框中输入一个空格，显示“文章长度超出限制了呢，已输入2个字符，还可以输入-9998个字符”，删掉空格，显示“文章长度超出限制了呢，已输入1个字符，还可以输入-9999个字符”
 - 更新：不只是空格，回车，tab等键也是一样，输入十个字符以上时，恢复正常

**Comment by Aria-K-Alethia** [comment]
感谢提醒，已经解决。
